services:
  web:
    build: .
    command: bash -c "./app.sh"
    ports:
      - 8004:8000
    env_file:
      - .dock.env
    depends_on:
      - db

  faststream:
    build: .
    command: faststream run src.infrastructure.broker.consumers.user:app
    env_file:
      - .dock.env
    depends_on:
      - db
      - web

  db:
    hostname: postgres
    image: postgres:15.3
    expose:
      - 5432
    env_file:
      - .dock.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}